# ================================================
# Grafana Data Sources Configuration
# Prometheus接続設定
# ================================================

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      keepCookies: []
      timeInterval: 15s
