# ================================================
# ProcureERP Production HPA Patches
# 本番環境Horizontal Pod Autoscaler設定
# ================================================

# Backend HPA - Production
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: procure-erp-backend-hpa
  annotations:
    autoscaling.alpha.kubernetes.io/metrics: '[{"type":"Resource","resource":{"name":"cpu","target":{"type":"Utilization","averageUtilization":70}}},{"type":"Resource","resource":{"name":"memory","target":{"type":"Utilization","averageUtilization":80}}}]'
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","reason":"SucceededRescale"}]'
    
spec:
  minReplicas: 5
  maxReplicas: 20
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: procure-erp-backend
  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
  
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 5
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 300
      - type: Pods
        value: 2
        periodSeconds: 300
      selectPolicy: Min

---
# Frontend HPA - Production
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: procure-erp-frontend-hpa
  annotations:
    autoscaling.alpha.kubernetes.io/metrics: '[{"type":"Resource","resource":{"name":"cpu","target":{"type":"Utilization","averageUtilization":75}}},{"type":"Resource","resource":{"name":"memory","target":{"type":"Utilization","averageUtilization":85}}}]'
    
spec:
  minReplicas: 5
  maxReplicas: 15
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: procure-erp-frontend
  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
  - type: Pods
    pods:
      metric:
        name: nginx_active_connections
      target:
        type: AverageValue
        averageValue: "50"
  
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 3
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 300
      - type: Pods
        value: 1
        periodSeconds: 300
      selectPolicy: Min

---
# Nginx HPA - Production
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: procure-erp-nginx-hpa
  annotations:
    autoscaling.alpha.kubernetes.io/metrics: '[{"type":"Resource","resource":{"name":"cpu","target":{"type":"Utilization","averageUtilization":80}}},{"type":"Resource","resource":{"name":"memory","target":{"type":"Utilization","averageUtilization":85}}}]'
    
spec:
  minReplicas: 3
  maxReplicas: 10
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: procure-erp-nginx
  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
  - type: Pods
    pods:
      metric:
        name: nginx_requests_per_second
      target:
        type: AverageValue
        averageValue: "200"
  
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 300
      - type: Pods
        value: 1
        periodSeconds: 300
      selectPolicy: Min

---
# Postgres HPA - Production (Read Replicas)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: procure-erp-postgres-read-hpa
  annotations:
    autoscaling.alpha.kubernetes.io/metrics: '[{"type":"Resource","resource":{"name":"cpu","target":{"type":"Utilization","averageUtilization":70}}},{"type":"Resource","resource":{"name":"memory","target":{"type":"Utilization","averageUtilization":80}}}]'
    
spec:
  minReplicas: 2
  maxReplicas: 5
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: procure-erp-postgres-read
  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: postgres_active_connections
      target:
        type: AverageValue
        averageValue: "80"
  
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 50
        periodSeconds: 120
      - type: Pods
        value: 1
        periodSeconds: 120
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 25
        periodSeconds: 600
      - type: Pods
        value: 1
        periodSeconds: 600
      selectPolicy: Min

---
# Redis HPA - Production (Cluster Mode)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: procure-erp-redis-hpa
  annotations:
    autoscaling.alpha.kubernetes.io/metrics: '[{"type":"Resource","resource":{"name":"cpu","target":{"type":"Utilization","averageUtilization":75}}},{"type":"Resource","resource":{"name":"memory","target":{"type":"Utilization","averageUtilization":85}}}]'
    
spec:
  minReplicas: 3
  maxReplicas: 8
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: procure-erp-redis
  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
  - type: Pods
    pods:
      metric:
        name: redis_connected_clients
      target:
        type: AverageValue
        averageValue: "100"
  - type: Pods
    pods:
      metric:
        name: redis_commands_per_second
      target:
        type: AverageValue
        averageValue: "1000"
  
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 90
      policies:
      - type: Percent
        value: 100
        periodSeconds: 90
      - type: Pods
        value: 2
        periodSeconds: 90
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 300
      - type: Pods
        value: 1
        periodSeconds: 300
      selectPolicy: Min
