# ================================================
# ProcureERP Kubernetes Secrets Template
# 企業級機密情報管理
# 注意: 本番環境では外部シークレット管理システム使用推奨
# ================================================

apiVersion: v1
kind: Secret
metadata:
  name: procure-erp-secrets
  namespace: procure-erp
  labels:
    app: procure-erp
    component: secrets
type: Opaque
stringData:
  # Database Credentials (Base64エンコード済み値に置換)
  DATABASE_URL: "postgresql://username:password@postgres:5432/procure_erp"
  DATABASE_USERNAME: "procure_user"
  DATABASE_PASSWORD: "secure_password_here"
  
  # Redis Credentials
  REDIS_URL: "redis://redis:6379"
  REDIS_PASSWORD: "redis_password_here"
  
  # JWT Secrets
  JWT_SECRET: "jwt_secret_key_here_minimum_256_bits"
  JWT_REFRESH_SECRET: "jwt_refresh_secret_key_here"
  
  # Auth0 Configuration
  AUTH0_DOMAIN: "your-domain.auth0.com"
  AUTH0_CLIENT_ID: "auth0_client_id_here"
  AUTH0_CLIENT_SECRET: "auth0_client_secret_here"
  AUTH0_AUDIENCE: "https://api.procure-erp.com"
  AUTH0_CALLBACK_URL: "https://procure-erp.com/callback"
  
  # Session Secrets
  SESSION_SECRET: "session_secret_key_here"
  CSRF_SECRET: "csrf_secret_key_here"
  
  # Email Configuration (SMTP)
  SMTP_HOST: "smtp.example.com"
  SMTP_PORT: "587"
  SMTP_USERNAME: "noreply@procure-erp.com"
  SMTP_PASSWORD: "smtp_password_here"
  SMTP_FROM_EMAIL: "noreply@procure-erp.com"
  SMTP_FROM_NAME: "ProcureERP"
  
  # S3/Object Storage Credentials
  AWS_ACCESS_KEY_ID: "aws_access_key_here"
  AWS_SECRET_ACCESS_KEY: "aws_secret_key_here"
  AWS_REGION: "ap-northeast-1"
  AWS_BUCKET_NAME: "procure-erp-uploads"
  
  # Monitoring & Observability
  NEW_RELIC_LICENSE_KEY: "new_relic_license_key_here"
  SENTRY_DSN: "sentry_dsn_here"
  DATADOG_API_KEY: "datadog_api_key_here"
  
  # External API Keys
  STRIPE_SECRET_KEY: "stripe_secret_key_here"
  SLACK_WEBHOOK_URL: "slack_webhook_url_here"

---
# TLS Certificate Secret (例: Let's Encrypt証明書)
apiVersion: v1
kind: Secret
metadata:
  name: procure-erp-tls
  namespace: procure-erp
  labels:
    app: procure-erp
    component: tls
type: kubernetes.io/tls
data:
  # Base64エンコードされた証明書データ
  tls.crt: LS0tLS1CRUdJTi... # 実際の証明書に置換
  tls.key: LS0tLS1CRUdJTi... # 実際の秘密鍵に置換
